pm install-existing com.amazon.appmanager
pm install-existing com.android.apps.tag
pm install-existing com.android.backupconfirm
pm install-existing com.android.bookmarkprovider
pm install-existing com.android.companiondevicemanager
pm install-existing com.android.egg
pm install-existing com.android.frameworkhwext.honor
pm install-existing com.android.frameworkres.overlay
pm install-existing com.android.hwmirror
pm install-existing com.android.inputdevices
pm install-existing com.android.keychain
pm install-existing com.android.keyguard
pm install-existing com.android.managedprovisioning
pm install-existing com.android.partnerbrowsercustomizations.tmobile
pm install-existing com.android.providers.partnerbookmarks
pm install-existing com.android.sharedstoragebackup
pm install-existing com.android.stk
pm install-existing com.android.storagemanager
pm install-existing com.example.android.notepad
pm install-existing com.facebook.appmanager
pm install-existing com.google.android.apps.tachyon
pm install-existing com.google.android.feedback
pm install-existing com.google.android.gm
pm install-existing com.google.android.gms.location.history
pm install-existing com.google.android.marvin.talkback
pm install-existing com.google.android.onetimeinitializer
pm install-existing com.google.android.partnersetup
pm install-existing com.google.android.projection.gearhead
pm install-existing com.google.android.videos
pm install-existing com.hicloud.android.clone
pm install-existing com.hisi.mapcon
pm install-existing com.hisi.supl
pm install-existing com.huawei.KoBackup
pm install-existing com.huawei.android.FMRadio
pm install-existing com.huawei.android.chr
pm install-existing com.huawei.android.dsdscardmanager
pm install-existing com.huawei.android.hsf
pm install-existing com.huawei.android.hwaps
pm install-existing com.huawei.android.hwupgradeguide
pm install-existing com.huawei.android.instantshare
pm install-existing com.huawei.android.internal.app
pm install-existing com.huawei.android.karaoke
pm install-existing com.huawei.android.pushagent
pm install-existing com.huawei.android.totemweather
pm install-existing com.huawei.appmarket
pm install-existing com.huawei.assetsync
pm install-existing com.huawei.assetsyncservice
pm install-existing com.huawei.behaviorauth
pm install-existing com.huawei.contacts.sync
pm install-existing com.huawei.contactscamcard
pm install-existing com.huawei.fastapp
pm install-existing com.huawei.featurelayer.sharedfeature.map
pm install-existing com.huawei.fido.uafclient
pm install-existing com.huawei.gameassistant
pm install-existing com.huawei.hiaction
pm install-existing com.huawei.hicloud
pm install-existing com.huawei.hidisk
pm install-existing com.huawei.hifolder
pm install-existing com.huawei.himovie.overseas
pm install-existing com.huawei.hitouch
pm install-existing com.huawei.hiview
pm install-existing com.huawei.hiviewtunnel
pm install-existing com.huawei.hwasm
pm install-existing com.huawei.hwdetectrepair
pm install-existing com.huawei.hwid
pm install-existing com.huawei.hwstartupguide
pm install-existing com.huawei.iaware
pm install-existing com.huawei.iconnect
pm install-existing com.huawei.intelligent
pm install-existing com.huawei.mmitest
pm install-existing com.huawei.parentcontrol
pm install-existing com.huawei.pcassistant
pm install-existing com.huawei.phoneservice
pm install-existing com.huawei.recsys
pm install-existing com.huawei.securitymgr
pm install-existing com.huawei.synergy
pm install-existing com.huawei.tips
pm install-existing com.huawei.trustagent
pm install-existing com.huawei.trustcircle
pm install-existing com.huawei.vassistant
pm install-existing com.zhiliaoapp.musically
pm install-existing de.telekom.tsc
pm install-existing hu.telekom.telekomapp
pm install-existing telekom.hu.android.mobilvasarlas
