pm uninstall --user 0 com.amazon.appmanager
pm uninstall --user 0 com.android.apps.tag
pm uninstall --user 0 com.android.backupconfirm
pm uninstall --user 0 com.android.bookmarkprovider
pm uninstall --user 0 com.android.companiondevicemanager
pm uninstall --user 0 com.android.egg
pm uninstall --user 0 com.android.frameworkhwext.honor
pm uninstall --user 0 com.android.frameworkres.overlay
pm uninstall --user 0 com.android.hwmirror
pm uninstall --user 0 com.android.inputdevices
pm uninstall --user 0 com.android.keychain
pm uninstall --user 0 com.android.keyguard
pm uninstall --user 0 com.android.managedprovisioning
pm uninstall --user 0 com.android.partnerbrowsercustomizations.tmobile
pm uninstall --user 0 com.android.providers.partnerbookmarks
pm uninstall --user 0 com.android.sharedstoragebackup
pm uninstall --user 0 com.android.stk
pm uninstall --user 0 com.android.storagemanager
pm uninstall --user 0 com.example.android.notepad
pm uninstall --user 0 com.facebook.appmanager
pm uninstall --user 0 com.google.android.apps.tachyon
pm uninstall --user 0 com.google.android.feedback
pm uninstall --user 0 com.google.android.gm
pm uninstall --user 0 com.google.android.gms.location.history
pm uninstall --user 0 com.google.android.marvin.talkback
pm uninstall --user 0 com.google.android.onetimeinitializer
pm uninstall --user 0 com.google.android.partnersetup
pm uninstall --user 0 com.google.android.projection.gearhead
pm uninstall --user 0 com.google.android.videos
pm uninstall --user 0 com.hicloud.android.clone
pm uninstall --user 0 com.hisi.mapcon
pm uninstall --user 0 com.hisi.supl
pm uninstall --user 0 com.huawei.KoBackup
pm uninstall --user 0 com.huawei.android.FMRadio
pm uninstall --user 0 com.huawei.android.chr
pm uninstall --user 0 com.huawei.android.dsdscardmanager
pm uninstall --user 0 com.huawei.android.hsf
pm uninstall --user 0 com.huawei.android.hwaps
pm uninstall --user 0 com.huawei.android.hwupgradeguide
pm uninstall --user 0 com.huawei.android.instantshare
pm uninstall --user 0 com.huawei.android.internal.app
pm uninstall --user 0 com.huawei.android.karaoke
pm uninstall --user 0 com.huawei.android.pushagent
pm uninstall --user 0 com.huawei.android.totemweather
pm uninstall --user 0 com.huawei.appmarket
pm uninstall --user 0 com.huawei.assetsync
pm uninstall --user 0 com.huawei.assetsyncservice
pm uninstall --user 0 com.huawei.behaviorauth
pm uninstall --user 0 com.huawei.contacts.sync
pm uninstall --user 0 com.huawei.contactscamcard
pm uninstall --user 0 com.huawei.fastapp
pm uninstall --user 0 com.huawei.featurelayer.sharedfeature.map
pm uninstall --user 0 com.huawei.fido.uafclient
pm uninstall --user 0 com.huawei.gameassistant
pm uninstall --user 0 com.huawei.hiaction
pm uninstall --user 0 com.huawei.hicloud
pm uninstall --user 0 com.huawei.hidisk
pm uninstall --user 0 com.huawei.hifolder
pm uninstall --user 0 com.huawei.himovie.overseas
pm uninstall --user 0 com.huawei.hitouch
pm uninstall --user 0 com.huawei.hiview
pm uninstall --user 0 com.huawei.hiviewtunnel
pm uninstall --user 0 com.huawei.hwasm
pm uninstall --user 0 com.huawei.hwdetectrepair
pm uninstall --user 0 com.huawei.hwid
pm uninstall --user 0 com.huawei.hwstartupguide
pm uninstall --user 0 com.huawei.iaware
pm uninstall --user 0 com.huawei.iconnect
pm uninstall --user 0 com.huawei.intelligent
pm uninstall --user 0 com.huawei.mmitest
pm uninstall --user 0 com.huawei.parentcontrol
pm uninstall --user 0 com.huawei.pcassistant
pm uninstall --user 0 com.huawei.phoneservice
pm uninstall --user 0 com.huawei.recsys
pm uninstall --user 0 com.huawei.securitymgr
pm uninstall --user 0 com.huawei.synergy
pm uninstall --user 0 com.huawei.tips
pm uninstall --user 0 com.huawei.trustagent
pm uninstall --user 0 com.huawei.trustcircle
pm uninstall --user 0 com.huawei.vassistant
pm uninstall --user 0 com.zhiliaoapp.musically
pm uninstall --user 0 de.telekom.tsc
pm uninstall --user 0 hu.telekom.telekomapp
pm uninstall --user 0 telekom.hu.android.mobilvasarlas
